
import Container from "../components/container";
import Layout from "../components/Layout/Layout";

const Terms = () => {
  return (
    
 <Layout>
<Container>


<h1 className = "text-xl xl:mt-24 font-bold leading-snug tracking-tight text-gray-800 lg:text-3xl lg:leading-tight xl:text-4xl xl:leading-tight dark:text-white" ><strong>Teillo Terms and Conditions</strong></h1> <br></br>
<p><strong><strong>Updated 25 July 2023</strong></strong></p> <br></br> <br></br>
<br></br>
<p>Welcome to Teillo. Please read on to learn the rules and restrictions that govern your use of our website(s), mobile app(s), products, services, applications, and or other online or offline communications (the &ldquo;Services&rdquo;). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at:</p>
<br />
<p>Email: <a href="mailto:info@teillo.com">info@teillo.com</a></p>
<p>Phone: <a href="tel:+27622762061">+27 60 666 6687</a></p>
<p>Address: 27 Main Road, Rondebosch, Cape Town, WC, 7700</p>
<br />
<br />
<p>PLEASE CAREFULLY READ THESE TERMS AND CONDITIONS OF USE BEFORE USING THIS SITE OR ANY OF THE SERVICES AND APPLICATIONS.&nbsp;</p>
<br />
<p>If you do not agree to these Terms and Conditions, please do not access or use this website or the products or services offered thereby.</p>
<p>Welcome to Teillo. These terms and conditions (&ldquo;Agreement&rdquo;) apply to Teillo Pty(Ltd). (&ldquo;Teillo&rdquo;) website (Teillo.co.za) and the related mobile application and/or selected other domains, existing or future, and related content, products and services (collectively, the &ldquo;Services&rdquo;) As used in this Agreement, &ldquo;Teillo,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo; shall mean Teillo Pty(Ltd).</p>
<p>By accessing or using our Services, whether or not you register to use the Service, you agree the terms of this Agreement and to the collection, use and disclosure of your information as set forth in to our&nbsp;Privacy Policy, which establish a contractual relationship between you and Teillo. This Agreement supersedes prior agreements or arrangements with you. You should review the Agreement before providing us with any information.</p>
<ol>
<li>As a condition of this Agreement, you further acknowledge that we may, in our sole discretion, modify this Agreement at any time by providing notice. That notice may be given by notification through our website or mobile applications or by e-mail, or</li>
<li>by posting a revision to these Terms and Conditions and changing the last updated notice above. Your continued access or use of the Services after such notice or posting constitutes your consent to be bound by the Agreement, as amended. You affirm that you will review this Agreement periodically, so that you are aware of any and all modifications made to this Agreement.</li>
</ol>
<p>Supplemental terms may apply to certain Services, such as policies for a particular event, activity or promotion, and such supplemental terms, if any, will be disclosed to you in connection with the applicable Services. Supplemental terms are in addition to, and shall be deemed a part of, the Agreement for the purposes of the applicable Services. Supplemental terms shall prevail over the terms of this Agreement in the event of a conflict with respect to the applicable Services.</p>
<br></br><h2><strong><strong>THE SERVICES</strong></strong></h2> <br></br>
<p>Teillo is an on-demand laundry and dry cleaning delivery service that enable users to schedule the delivery using Teillo&rsquo;s mobile applications or website which is provided as part of the Services (each of the mobile applications and the website is an &ldquo;Application&rdquo;). After scheduling the reservation using the Application, a W2 employee, working with Teillo, will pick up and deliver the user&rsquo;s laundry.</p>
<br></br><h2><strong><strong>OWNERSHIP AND RESTRICTIONS ON USE OF MATERIALS</strong></strong></h2>
<p>The Services, including, but not limited to, the text, content, photographs, images, video, audio, graphics, and any software (including any files or images incorporated in or generated by the software, or any data accompanying the software) available on or through the Services, or contained in the Services (&ldquo;Materials&rdquo;) are owned and operated by Teillo. The Services and the Materials are protected by copyright, trademark, trade dress, domain name, patent, trade secret, international treaties and/or other proprietary rights and laws of the Republic of South Africa and other countries.</p>
<p>Except as otherwise indicated in the Services and except for the trademarks, service marks and trade names of other companies that are or may be displayed in the Services, all trademarks, service marks, trade dress and trade names are proprietary to Teillo.<br />By accessing and using the Services, you acknowledge and agree to abide by all applicable intellectual property laws, as well as any additional notices or restrictions contained in this Agreement.</p>
<p>No Materials from the Services and Applications may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except that you may download one copy of the Materials on any single computer for your non-commercial use only, provided that you keep intact all copyright and other proprietary notices. You may not use any automated device, computer program, tool, algorithm, bot or similar process to mine or systematically scrape or extract Materials from this website. Modification of the Materials or unauthorized use of the Materials for any other purpose is a violation of Teillo&rsquo;s trademark, copyright, trade dress and other proprietary rights. The use of any such Materials on any other site or networked computer environment is prohibited unless approved in advance and in writing by Teillo.</p>
<p>In the event that you download any software from the Services, the software, including any files, images incorporated in or generated by the software, and data accompanying the software (collectively, the &ldquo;Software&rdquo;) is non-exclusively licensed to you by Teillo. Teillo does not transfer title to the Software to you. Teillo retains full and complete title to the Software, and all intellectual property rights therein. You shall not redistribute, sell, decompile, reverse engineer, disassemble, or otherwise reduce the Software to a human-perceivable form.</p>
<p>Nothing contained in the Services should be construed as granting, by implication, estoppel or otherwise, any license or right to use any of the Materials or proprietary content without the express written permission of Teillo or such other party as may own the proprietary rights.</p>
<br></br><h2><strong><strong>LICENSE</strong></strong></h2>
<p>Subject to your compliance with the terms of the Agreement, Teillo grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to:&nbsp;</p>
<ol>
<li>&nbsp;access and use the Applications on your personal device solely in connection with your use of the Services; and&nbsp;</li>
<li>access and use any content, information and related Materials that may be made available through the Services, in each case solely for your personal, non-commercial use. Any rights not expressly granted herein are reserved by Teillo and Teillo&rsquo;s licensors.
<br></br>
<h2><strong><strong>USE OF THE SERVICES</strong></strong></h2>
</li>
</ol>
<br></br>
<p><strong>USER REQUIREMENTS AND CONDUCT/USER ACCOUNTS</strong></p>
<p>In order to use most aspects of the Services, you must register for and maintain an active personal user Services account (&ldquo;Account&rdquo;). You must be at least 12 years of age to obtain an Account. Account registration requires you to submit to Teillo certain personal information, such as your name, address and mobile phone number, as well as at least one valid credit or debit card. You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired credit card on file, may result in your inability to access and use the Services or Teillo&rsquo;s termination of this Agreement with you. You are responsible for all activity that occurs under your Account, and, as such, you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by Teillo in writing, you may only possess one Account.</p>
<p>The Service is not available for use by persons under the age of 12. You may not authorize third parties to use your Account, and you may not allow persons under the age of 12 to use the Services unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when using the Services, and you may only use the Services for lawful purposes. In certain instances Teillo or a Third Party Contractor may require you to provide proof of identity to access or use the Services, and you agree that you may be denied access or use of the Services if you refuse to provide proof of identity.</p>
<br></br>
<p><strong><strong>TEXT AND WHATSAPP MESSAGES</strong></strong></p>
<p>By creating an Account, you agree that the Services may send you informational text (SMS) messages and WhatsApp messages as part of the normal business operation of your use of the Services. You may opt-out of receiving text (SMS) messages or WhatsApp messages from Teillo at any time by sending a request to support@Teillo.co.za or by replying STOP to any message you receive. You acknowledge that opting out of receiving text (SMS) messages may impact your use of the Services.</p>
<br></br>

<p><strong><strong>PROMOTIONAL CODES AND SPECIAL OFFERS</strong></strong></p>
<p>Teillo may, in Teillo&rsquo;s sole discretion, create promotional codes that may be redeemed for Account credit or other features or benefits related to a Third Party Contractors, subject to terms that Teillo may establish on a per promotional code basis (&ldquo;Promo Codes&rdquo;).<br />You agree that Promo Codes:&nbsp;</p>
<ol>
<li>must be used for the intended audience and purpose, and in a lawful manner;&nbsp;</li>
<li>may not be duplicated, sold or transferred in any manner, or made available to the general public, unless expressly permitted by Teillo, in advance in writing;</li>
<li>may be disabled by Teillo at any time for any reason without liability to Teillo;&nbsp;</li>
<li>are not valid for cash; and&nbsp;</li>
<li>may expire prior to your use. Teillo reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that Teillo determines or believes that the use or redemption of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms or the terms of the Agreement.</li>
</ol>
<h2><br /><strong><strong>MINIMUM PRICE ORDER</strong></strong></h2> 
<p>The minimum order price is as cited on Teillo&rsquo;s Services and may change from time to time.</p>
<br></br>
<h2><strong><strong>NETWORK ACCESS AND DEVICES</strong></strong></h2> 
<p>You are responsible for obtaining the data network access necessary to use the Services. Your mobile network&rsquo;s data and messaging rates and fees may apply if you access or use the Services from a wireless-enabled device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. Teillo does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.</p>
<br></br><h2><strong><strong>DAMAGED OR LOST ITEMS</strong></strong></h2> 
<p>It is our priority to supply the best care to your garment and we appreciate your trust.</p>
<br></br>
<h2> <strong><strong> MISSING ITEMS</strong></strong></h2> 
<p>While it is never our intention for an item to go missing, occasionally it can happen. If this is the case, please let us know immediately by calling our customer experience team at 068-590-0763or by emailing them at&nbsp;<a href="mailto:support@Lynen.co.za">support@Teillo.co.za</a>. Notifying the concierge or notifying Teillo via SMS is insufficient. In order to receive reimbursement, any missing item must be reported to our customer experience team within twenty four (24) hours of the delivery of the order, in order to ensure the maximum likelihood that it will be located. All claims are reviewed on a case-by-case basis. Items are considered lost ten (10) business days after the initial claim has been made. All decisions on lost items are in Teillo&rsquo;s sole discretion and are final.</p>
<br></br><h2><strong><strong>Reimbursement Guidelines</strong></strong></h2>
<p>For Wash and Fold/Hang Dry, Dry Cleaning and laundered shirts, any reimbursement for an item or order deemed lost by Teillo shall be limited to and shall not exceed five (5) times the charge for cleaning the lost item (not inclusive of tax and other fees) regardless of brand, price or condition of the garment, or R1000(one thousand rand only), whichever is lower. To the fullest extent permitted by law, Teillo&rsquo;s aggregate liability in connection with a lost item shall not exceed the foregoing amount. Teillo&rsquo;s offer for reimbursement is valid for seven (7) business days once the offer is made. Any attempts at redemption beyond that will be evaluated on a case by case basis. All decisions on lost items are in Teillo&rsquo;s sole discretion and are final.</p>
<br></br><p><strong><em>Exceptions to this missing items policy include:</em></strong></p>
<ol>
<li>Socks, which will be reimbursed at R50 per pair in Teillo credit, regardless of brand, price or condition,</li>
<li>Teillo does not accept liability for any personal laundry bags that are not Teillo branded bags,</li>
<li>Teillo does not take responsibility for any loose items lost when submitted in a Teillo bag, such as watches, jewellery, cufflinks, money, wallets, etc. and shall have no liability for such items,</li>
<li>Teillo additionally is not liable for damage caused by you not selecting the correct service when placing an order (e.g. selecting wash and fold instead of dry cleaning, forgetting to add hang dry service), or when items are sent in incorrect bags (e.g. dry cleaning placed inside a labelled wash and fold bag). Teillo is also not liable for damage caused by, but not limited to loose items like pens and lipstick.</li>
</ol>
<p>Any damaged items must be reported by calling us at +27 68 590 0763 or by emailing us at&nbsp;<a href="mailto:info@teillo.co.za">support@teillo.co</a>.za&nbsp;within twenty four (24) hours of delivery of the order. Notifying the concierge or notifying Teillo via SMS is insufficient. All damaged items must inspected by Teillo through digital photos of each damaged item, within seven (7) days of delivery of the order. All decisions on damaged items are in Teillo&rsquo;s sole discretion and are final.</p>
<br></br><h2><strong><strong>DAMAGED ITEMS</strong></strong></h2>
<p>Although we do our best to prevent any damages to your garment, unfortunately every garment, regardless of brand or quality, will wear out over time, and there is nothing Teillo can do to predict when this will happen, or prevent it. For damage related to normal wear and tear, Teillo does not provide reimbursement or compensation. Per industry standards, the following are considered to be normal wear and tear:</p>
<ol>
<li>Shrinkage from repeated laundering</li>
<li>Colour fading</li>
<li>Small holes or tears</li>
<li>Discoloration caused by hygiene or beauty products (deodorant, perfume, cologne)</li>
<li>Button damage</li>
<li>Thinning of fabric

<br></br>

<br></br><h2><strong><strong>Reimbursement Guidelines</strong></strong></h2>
</li>
</ol>
<p>For any items, regardless of service, deemed damaged outside of the above, Teillo may reimburse you by paying up to five (5) times the charge for cleaning the item (not inclusive of tax and other fees) for which the damage occurred regardless of brand, price or condition of the garment, or R1000, whichever is lower. To the fullest extent permitted by law, Teillo&rsquo;s aggregate liability in connection with a damaged item shall not exceed the foregoing amount. Teillo&rsquo;s offer for reimbursement is valid for seven (7) business days once the offer is made. Any attempts at redemption beyond that will be evaluated on a case by case basis. All decisions on damaged items are in Teillo&rsquo;s sole discretion and are final.</p>
<p>In order to receive reimbursement, the damaged item must be given to Teillo to be inspected and subsequently donated. If you wish to keep your item, only reimbursement in Teillo credit will be offered.</p>
<br></br><h2><strong><strong>PICK UP AND DELIVERY</strong></strong></h2>
<p>Our goal is to provide valuable and timely service to all of our customers and partners. If you cancel a pickup less than 30 minutes before your requested time, rescheduled a delivery after the designated time for change (varies by location and city), or if our partners cannot deliver or pickup an order because you or your designee failed to appear, we may charge a cancellation fee in a reasonable amount (changes per location and city).</p>
<p>We hope to provide a convenient service to all our customers and can leave orders outside residences or with a doorman, provided the customer gives written consent. However, once delivery has been made, we will not be held responsible or liable for the loss or damage of any items. It is the customer&rsquo;s sole responsibility to ensure the safety of items after delivery by Teillo. You have an option to ask us to leave your laundry with the doormen or other location, but Teillo will not be responsible for any lost cause as a result.</p>
<br></br><h2><strong><strong>INVENTORY</strong></strong></h2>
<p>Teillo reserves the right to keep records of your garments and retain, store, display or reproduce such records which may include images or photographs, and associate such records with your name or other profile information for commercially reasonable periods for archival, inventory purposes, quality control, loss prevention, and or data collection.</p>
<h2><br /><strong><strong>USER CONTENT AND INTERACTIVE AREAS</strong></strong></h2>
<p>We may provide interactive opportunities in the Services, including, without limitation, user ratings and reviews, saved favourites and saved instructions, (collectively, &ldquo;Interactive Areas&rdquo;) for the enjoyment of our users.</p>
<p>You represent and warrant that you are the owner or otherwise have the right to provide any information, comments, reviews, ratings or other materials or content submitted, posted or otherwise transmitted to the Services (&ldquo;User Content&rdquo;). In addition, in consideration of the Services accepting User Content, you hereby grant to Teillo an irrevocable, transferable, paid up, royalty-free, perpetual, non-exclusive worldwide sub-licensable license to use, copy, print, display, modify, edit, remove, publicly perform, translate and create derivative works from and distribute or otherwise use and reproduce User Content on the Services and in all forms of media now known or hereafter invented, including but not limited to such uses as on and in the Services throughout the world in all forms of media now known or hereafter invented in perpetuity (collectively, the &ldquo;Uses&rdquo;) and the right to, in Teillo&rsquo;s sole option and discretion, attribute such User Content to the user submitting the User Content. In consideration of submitting User Content, you consent to the Uses of the User Content without further consideration, compensation, attribution, notification or other additional consideration and to Teillo&rsquo;s disclosure of any information related to your use of the Services in any capacity in connection with Teillo&rsquo;s display of your User Content on the Services. You also agree to indemnify and hold Teillo harmless from any claim or demand, including reasonable attorneys&rsquo; fees, made by any party arising out of the Uses of the User Content that you submit on our Services. You waive any rights you may have in having the User Content edited, altered or changed in any manner not acceptable to you.</p>
<p>Some submissions or postings by users to certain parts of the Services, including, without limitation, Interactive Areas, will be public and posted in public areas on our Services. Teillo and any contract or operational providers that conduct, operate and/or manage any portion of the Services will not be responsible for the action of any users or third parties with respect to any information, materials or content posted, uploaded or transmitted on the Services.</p>
<p>By participating in any of the aforementioned activities, all users agree to follow the Services standards of conduct. Teillo reserve the right to change, delete or remove, in part or in full, any postings in Interactive Areas and to terminate or suspend access to such areas of the Services for conduct that we believe, in our sole discretion, interferes with other peoples&rsquo; enjoyment of our Services. Teillo will also cooperate with local, state and/or federal authorities to comply with applicable law.</p>
<br /><h2><strong><strong>NO UNLAWFUL OR PROHIBITED USE/MONITORING OF SERVICES</strong></strong></h2>
<p>By participating in any of the aforementioned activities, all users agree to follow any standards of conduct posted through the Services. Without limiting the foregoing, you shall not provide any User Content that is infringing, defamatory, unlawful, obscene, sexually explicit, harassing, threatening, abusive, illegal or otherwise improper. Teillo reserve the right to change, delete or remove, in part or in full, any User Content in Interactive Areas and to terminate or suspend access to such areas of the Services for conduct that we believe, in our sole discretion, violates acceptable use standards or interferes with other peoples&rsquo; enjoyment of our Services. Teillo will also cooperate with local, state and/or federal authorities to comply with applicable law.</p>
<p>Teillo reserves the right, in its sole discretion, to monitor any and all use of the Services.</p>
<ul>
<li>
<br /><h2><strong><strong>VIOLATIONS OF THE AGREEMENT</strong></strong></h2>
</li>
</ul>
<p>Teillo reserves the right to seek all remedies available at law and in equity for violations of the Agreement, including the right to block access from a particular Internet address to the Services.</p>
<ul>
<li><br />
<h2><strong><strong>TERMINATION OF SERVICES</strong></strong></h2>
</li>
</ul>
<p>Teillo reserves the right, in its sole discretion, to terminate your access to the Applications and Services or any portion thereof at any time. We will use commercially reasonable efforts to attempt to notify you of such termination. Teillo reserves the right to cancel Services and/or your Account for cause, such as if a delivery site is unsuitable, inaccessible or unsafe, or due to force majeure or inappropriate or abusive activity by you or third parties. In the event of any termination, you will be responsible for paying for Services performed prior to termination.</p>
<p>The Agreement shall continue to apply for as long as you use the Services, and any provisions contained herein which by their nature or effect are required or intended to be observed after termination will survive termination and remain binding, including the provisions regarding your indemnification obligations, our limitations of liability and the resolution of disputes through arbitration.</p>
<h2><br /><strong><strong>CANCELLATION POLICY</strong></strong></h2>
<ul>
<li>Teillo assesses a R250 cancellation fee to appointments cancelled within 24 hours of your scheduled appointment.</li>
<li>Same day cancellations will result in a R500 cancellation fee.</li>
<li>If you have a recurring weekly or bi-weekly service, you are still responsible to cancel an appointment if necessary more than 24 hours prior to your scheduled appointment. If this does not occur, you will be assessed a cancellation fee.</li>
</ul>
<h2><br /><br /><strong><strong>PAYMENT</strong></strong></h2>
<ul>
<li>You understand that use of the Services may result in payments by you for the services you receive (&ldquo;Charges&rdquo;). After you have received the service ordered through your use of the Service and Applications, Teillo will process payment of the applicable Charges, using the preferred payment method designated in your Account, and will send you a receipt by email.</li>
</ul>
<ul>
<li>Charges will be inclusive of applicable taxes where required by law. Charges paid by you are final and non-refundable, unless otherwise determined by Teillo. Any request for lower Charges or disputes regarding the Charges should be addressed to Teillo by contacting&nbsp;<a href="mailto:support@Lynen.co.zam">support@Teillo.co.za</a></li>
</ul>
<ul>
<li>If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that Teillo may use a secondary payment method in your Account, if available. Please note that in the event you dispute any part of a valid Charge via chargeback, you agree that Teillo have the right at our option to pursue you for payment, to seek reimbursement of any related costs incurred by us, to turn any past due account over to collections and/or report delinquent payment to credit bureaus.</li>
</ul>
<ul>
<li>Teillo reserves the right to establish, remove and/or revise prospective Charges for any or all aspects of the Services at any time in Teillo&rsquo;s sole discretion. The Charges indicated via the Services at the time of your order shall apply (subject to any applicable discounts or promotions). Teillo may from time to time provide certain users with promotional offers and discounts that may result in different Charges for the same or similar Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you.</li>
</ul>
<h2><br /><strong><strong>DISCLAIMERS, LIMITATIONS OF LIABILITY, INDEMNITY</strong></strong></h2>
<ul>
<br /><br />
<li><strong>DISCLAIMER</strong></li>
</ul>
<p>The Materials and the Services are provided &ldquo;as is&rdquo; and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, Teillo and its officers, directors, employees, agents or representatives disclaim with respect to the Services and the Materials herein all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. It is your responsibility to carefully read and inspect any service or product you purchase through our Applications upon your receipt to determine safety and appropriateness for your consumption or use. Teillo does not represent or warrant that the functions contained in the Services will be uninterrupted or error-free, that defects will be corrected, or that the Services or the server that makes it available are free of viruses or other harmful components. Teillo does not warrant or make any representations regarding the use or the results of the use of the Materials and/or the Services in terms of their correctness, accuracy, reliability, timeliness, completeness, correctness, or otherwise. You (and not Teillo) assume the entire cost of all necessary servicing, repair, or correction. Applicable law may not allow the exclusion of implied warranties, so the above exclusion may not apply to you.</p>
<br /><h2><strong><strong>LIMITATION OF LIABILITY</strong></strong></h2>
<ul>
<li>To the fullest extent permitted by law, under no circumstances, including, but not limited to, negligence, shall Teillo or its officers, directors, employees, agents or representatives be liable to you or any third party for any special, consequential, incidental, direct, indirect, or punitive damages or any other loss or injury that result from the use of, or the inability to use, the Services or the Materials, even if Teillo or a Teillo authorized representative has been advised of the possibility of such damages.</li>
<li>&nbsp;Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages, so the above limitation may not apply to you. In no event shall Teillo have any liability for any damages, losses and other causes of action (whether in contract, tort (including, but not limited to, negligence), or otherwise) for accessing or using the Services or engaging the services of or purchasing product(s) of a third party through or after accessing the Services.&nbsp;</li>
<li>To the fullest extent permitted by law, your sole remedy with respect to lost or damaged items is as provided above in the sections entitled &ldquo;Damaged Items&rdquo; and &ldquo;Lost Items.&rdquo; If, notwithstanding the foregoing exclusions, it is determined that Teillo or its agents, employees, officers or directors is liable for damages, in no event shall Teillo&rsquo;s total liability to you for all damages, losses, and causes of action (whether in contract, tort or otherwise) related to the Applications or Services exceed the amount paid by you, if any, for such Application or Services.</li>
<li>These limitations do not purport to limit liability that cannot be excluded under the law in the jurisdiction of this Agreement. The limitations of liability in this section are not applicable to residents of New Jersey.&nbsp;</li>
<li>With respect to residents of New Jersey, Teillo and its affiliates are not liable for any damages unless such damages are the result of our negligent, reckless or intentional acts or omissions; and to the fullest extent permitted by law we are not liable for incidental, special or consequential damages.</li>
</ul><br />
<h2><strong><strong>USE OF LINKS</strong></strong></h2>
<ul>
<li>The Services may contain links to other websites and services which are developed, sponsored and/or maintained by third parties. Teillo does not review, monitor, operate or control any such third party website/services accessible through these links, and is not responsible for the content available on or through such third party websites/services.&nbsp;</li>
</ul>
<ul>
<li>By providing access to the linked websites/services, Teillo is not recommending or endorsing the products or services provided by the sponsor or owner of those websites/services. Teillo makes no guarantees, representations or warranties as to, and shall have no liability for, any electronic content delivered by any third party, including, without limitation, the accuracy or subject matter of any electronic content, or the use of any personal information you provide to any such website/services. You acknowledge and agree that use of such links is entirely at your own risk. Teillo reserves the right to discontinue links to any other website at any time and for any reason.</li>
<br /><li><strong><strong>INDEMNITY</strong></strong></li>
</ul>
<p>To the fullest extent permitted by law, You agree to indemnify and hold Teillo and its officers, directors, employees and agents, harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys&rsquo; fees), arising out of or in connection with:</p>
<ol>
<li>Your use of the Services;</li>
<li>Your breach or violation of any of this Agreement;&nbsp;</li>
<li>Teillo&rsquo;s use of your User Content; or&nbsp;</li>
<li>Your violation of the rights of any third party, including Third Party Contractors. This indemnification section does not apply to Teillo&rsquo;s own negligence, recklessness or intentional conduct.</li>
</ol>
<ul><br />
<li><strong><strong>MISCELLANEOUS</strong></strong></li>
</ul><br />
<h2><strong>GOVERNING LAW AND ARBITRATION</strong></h2>
<ul>
<li>You acknowledge and agree that your access to and use of the Services is subject to all applicable international, federal, state and local laws and regulations. The terms, conditions and policies contained in this Agreement shall be governed by and construed in accordance with the laws of the Republic of South Africa, without regard to any principles of conflicts of law.</li>
</ul><br />
<h2><strong>NOTICE</strong></h2>
<ul>
<li>Teillo may give notice by means of a general notice on the Services, electronic communication through an Application, electronic mail to your email address in your Account, or by written communication sent by first class mail or pre-paid post to your address in your Account. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to Teillo, with such notice deemed given when received by Teillo.</li>
</ul><br />
<h2><strong>GENERAL</strong></h2>
<ul>
<li>You may not assign the Agreement without Teillo&rsquo;s prior written approval. Teillo may assign this Agreement without your consent to:&nbsp;</li>
</ul>
<ol>
<li>a subsidiary or affiliate;&nbsp;</li>
<li>an acquirer of Teillo&rsquo;s equity, business or assets; or&nbsp;</li>
<li>a successor by merger. Any purported assignment in violation of this section shall be void. No joint venture, partnership, employment, or agency relationship exists between you, Teillo or any Third Party Contractor as a result of this Agreement or use of the Services. If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. Our failure to enforce any right or provision in this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Teillo in writing. Teillo&rsquo;s failure to enforce any part of this Agreement will not be considered a waiver. Any waiver by Teillo of any provision of this Agreement must be in writing. Unless otherwise specified herein, the Agreement constitutes the entire agreement between you and Teillo with respect to the website and Services and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and Teillo with respect thereto.</li>
</ol>
<p><br />Contact:&nbsp;<a href="mailto:info@teillo.co.za">info@teillo.co.za</a></p>
<p><br /><br /></p>
</Container>
</Layout>

     

  );
}

export default Terms;